app = "external-mem-kit"     # change this to your unique app name
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/data/data.db"
  ALLOWED_ORIGINS = "*"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 80