app = "external-mem-kit"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/data/data.db"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    port = 80