name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only

        - name: Set Fly Secrets
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          flyctl secrets set API_KEY="$API_KEY" --stage
          flyctl deploy --remote-only